### ISSUE TITLE
Missing runtime dependency on dry-equalizer

### ISSUE THREAD

**Issue by kwando** [dryrb/dry-data#11]
```vendor/bundle/gems/dry-data-0.3.0/lib/dry/data/constraints.rb:1:in `require': cannot load such file -- dry-equalizer (LoadError)```

**Comment by solnic** [comment]
oh, right, I forgot about this :( we don't have a hard dependency on dry-validation (which depends on dry-equalizer) but we do automatically require constrained type, which leads to this error. I will fix it. For now, please add `dry-validation` as your run-time dep, it will pull in dry-equalizer too

**Comment by solnic** [comment]
Fixed in 0.3.1. For constrained types you gotta add `dry-validation` to gemfile and also do `require "dry/data/type/constrained"`
