### ISSUE TITLE
Better error message when missing to specify "type" in struct

### ISSUE THREAD

**Issue by kwando** [dryrb/dry-data#6]
```ruby
class User < Dry::Data::Struct
  attribute :name, 'strict.string'
  attribute :email # <-- whoops I forgot the "type"
end
```
blows up with something like this:

```/vendor/bundle/gems/dry-data-0.0.1/lib/dry/data.rb:42:in `block in []': undefined method `match' for nil:NilClass (NoMethodError)```

which is quite ironic since the README states "(NoMethodError: undefined methodsize' for nil:NilClass` anyone?)" =P 

I'm aware this lib is not stable yet ;)

**Comment by solnic** [comment]
Thanks, I'll fix it at some point, I don't pay attention to this kind of details when API is unstable :)

**Comment by solnic** [comment]
ps. I see what you did there
