### ISSUE TITLE
Why default to a no-op?

### ISSUE THREAD

**Issue by booch** [dryrb/dry-data#7]
I'm confused by the example:

~~~ ruby
float["3.2"] # "3.2"
~~~

I don't see what `float` is doing for me, if it's not going to do anything with anything I pass to it. At the very least, I'd expect the default to be for `float` to do something, with the option of having it perform a no-op.

**Comment by solnic** [comment]
it defines a float type, treat it like something for type annotations, it's going to be a base for more complex types, ie a constrained float that must meet specific requirements.

**Comment by booch** [comment]
Yeah, but it's really surprising that the default behavior of the type is to not care if it's actually of that type.

**Comment by solnic** [comment]
As I said, this is the base construct for other types, when you actually don't want to have coercions at all, for type-checking there is `strict` category, for coercions there is `coercible` category, etc. A base is needed, the readme explains it. It represents information about the type, it's not meant to be used for coercion.

Simple annotations are useful too, ie when you trust the source to always provide already coerced input, but you do want to specify information about the types.
