### ISSUE TITLE
struct to struct feature?

### ISSUE THREAD

**Issue by MadBomber** [dryrb/dry-data#8]
One of the problems that I have collided with over the last 10 years of ruby-goodness is incompatible definitions of a point (e.g. location) in the world.  Strictly speaking a location is a latitude, longitude, altitude, and a datum such as WGS84.  This "type" is sometimes implemented as a class with attributes that intersect the four mentioned with various abbreviations such as lat, lng, long, alt etc.

Sometimes the "type" is implemented as a hash with again the same parade of abbreviations and full attribute names as the keys - sometimes as strings with various cases or symbols also with various cases.

Many times I have had to do one-off conversion methods to convert from one location type to another.

I sense the possibility with Dry::Data::Struct of constructing a family of types that are related - I guess thats why its called a family :)

```ruby
class Location < Dry::Data::Struct
  attribute :latitude,  "maybe.coercible.float"
  attribute :longitude, "maybe.coercible.float"
  attribute :altitude,  "maybe.coercible.float"
  attrobite :datum,     "coercible.string"
end

class AnotherLocation < Location
  attribute :lat,  renames: :latitude
  attribute :long, renames: :longitude
  attribute :alt,  renames: :altitude
end

class YetAnotherLocation < Location
  attribute :lat,  renames: :latitude,  "coercible.string"
  attribute :lng,  renames: :longitude, "coercible.string"
end

class AndYetAnotherLocation < Location
  attribute :lat,  renames: :latitude,  "coercible.hms_location"
  attribute :lng,  renames: :longitude, "coercible.hms_location"
end

class HmsLocation < Dry::Data::Struct
  attribute :hours,   "maybe.coercible.float"
  attribute :minutes, "maybe.coercible.float"
  attribute :seconds, "maybe.coercible.float"
end
```

I think I may have talked myself out of the idea.  The idea was that a super class can be the way in which two related sub-classes can be coerced;

**Comment by solnic** [comment]
Sorry but this is out of the scope of this library. We're only concerned with type definitions and rules for constructing a specific type instance. Renaming attributes is a data-mapping concern, related, but not exactly within the domain of dry-data.
